dqm/dqm/urls.py
from django.contrib import admin
from django.urls import path, include
# from myapp.views import hello
from myhome.views import index

from sources.views import sources
from display.views import display, create_display, show_display
from test.views import PersonView

import json
from django.http import JsonResponse


from Platform import data
def ajax_view(request, choice):
    streams = data.get_streams()
    if choice in streams:
        return JsonResponse(streams[choice], safe=False)
    else:
        return JsonResponse({})



urlpatterns = [
    path('admin/', admin.site.urls),
    # path('hello/', hello, name='home'),
    path('', index, name='home'),
    path('display/', display, name='display'),
    path('sources/', sources, name='sources'),
    path('create-display/', create_display, name='create display'),
    path('displays/<displayname>', show_display, name='show display'),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('test/', PersonView.as_view()),
    path('ajax/<choice>', ajax_view, name='ajax'),
]

# @home_bp.route("/create-display", methods=["GET", 'POST'])
# def create_display():
#     form_streams = ExampleForm()
#     streams = data.get_streams()
#     streamsls = []
#     # for key in streams:
#     #     streamsls.extend(list(streams[key]))
#     form_streams.choices.choices = [(elem, elem) for i, elem in enumerate (streamsls)]
#     # print(f'{form_streams.example.data=}')
#     # if form_streams.example.data == 1:
#     #     print('Creating new display')
#     #     # data.create_display(
#     """About page."""
#     if form_streams.choices.name:
#         print('Creating new display')
#         print(f'{form_streams.choices.data=}')

#         # source = form_streams.choices.food
#         source = form_streams.foodkind.data
#         displaystreams = {}
#         displaystreams[source] = form_streams.choices.data
#         print('STREAMS', displaystreams)
#         data.create_display(form_streams.name.data, displaystreams)

#     return render_template(
#         "create_display.jinja2",
#         title="Create displays",
#         template="home-template page",
#         form=form_streams,
#     )

# @home_bp.route('/create-display/get-streams/<streamname>')
# def get_streams(streamname):
#     streams = data.get_streams()
#     import json
#     if streamname not in streams:
#         return jsonify([])
#     else:
#         return jsonify(streams[streamname])

dqm/dqm/home/models.py
from django.db import models

# Create your models here.

dqm/display/views.py
from django.shortcuts import render

from Platform import data
from .dash_display import create_display as new_display

import django_tables2 as tables

from .models import Display

from django import forms
from .models import Text
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from crispy_forms.layout import Layout, Fieldset

class NameTable(tables.Table):
    name = tables.Column(attrs={'td': {'class': 'col-6'}}, linkify=True)
    description = tables.Column()

# Create your views here.
def display(request):

    # newnames = Display.objects.create(name='roland', description='this is a description')
    # obj = Display.objects.filter(name='this is a test')
    # obj.delete()
    newnames = Display.objects.all()
    # print(newnames[0].get_absolute_url)
    ls = []
    for s in newnames:
        ls.append(s)

    table = NameTable(ls)

    return render(request, 'index_display.dtl', context={'table': table})


displays = {}
def show_display(request, displayname):
    if displayname not in displays:
        app = new_display(displayname)
        displays[displayname] = app
    return render(request, 'display.dtl', context={'displayname': displayname})
    



def create_display(request):

    def get_form():

        possible_names = data.get_streams()
        # This is a hack to find all the available streams and pass them as possible choices
        # otherwise the form will complain that an invalid choice was chosen
        tmp = []
        for val in possible_names.values():
            tmp.extend(val)
        tmp = list(set(tmp))

        class ExampleForm(forms.Form):
            name = forms.CharField(label='Name of the display')
            description = forms.CharField(label='Short description')
            template = forms.CharField(label='Use the same template as')

            source = forms.ChoiceField(label='Source', choices= [(list(possible_names.keys())[i], list(possible_names.keys())[i]) for i in range(len(possible_names))])

            default_choices = [[tmp[i], tmp[i]] for i in range(len(tmp))]
            choices = forms.MultipleChoiceField(choices=(default_choices), required=False)

            def __init__(self, *args, **kwargs):
                super().__init__(*args, **kwargs)
                self.helper = FormHelper()
                self.helper.form_id = 'id-exampleForm'
                # self.helper.form_class = 'blueForms'
                self.helper.form_method = 'post'
                self.helper.form_action = ''

                self.helper.add_input(Submit('', 'Create display'))
                self.helper.layout = Layout(
                            Fieldset(
                        'first arg is the legend of the fieldset',
                        'name',
                        'description',
                        'template',
                        'source',
                        'choices',
                    )
                    )
        return ExampleForm

    Form = get_form();

    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = Form(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            print(f'Creating form with name {form.cleaned_data["name"]}')
            print(form.cleaned_data['name'])
            # data.create_display(form.cleaned_data['name'], {form.cleaned_data['source'][0] : form.cleaned_data['choices']})
            obj = Display.objects.filter(name=form.cleaned_data['name'])
            if not obj:
                print(form.cleaned_data['source'])
                print(form.cleaned_data['choices'])
                displays = {}
                for d in form.cleaned_data['choices']:
                    if 'raw_display' in d:
                        displays[d] = 'heatmap'
                    elif 'rmsm_display' in d:
                        displays[d] = 'scatter'
                    elif 'fft_sums_display' in d:
                        displays[d] = 'line'
                dataa = {form.cleaned_data['source']: displays}
                Display.objects.create(name=form.cleaned_data['name'],
                                       description=form.cleaned_data['description'],
                                       data=dataa
                                       )
            else:
                print(f'Panel with name {form.cleaned_data["name"]} already exists')

            # return HttpResponseRedirect('/thanks/')
        else:
            print('Form is not valid')
    else:
        form = Form()
    return render(request, 'create_display.dtl', context={'form': form})

dqm/dqm/home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html', context={'title': 'DUNEDAQ DQM Web Platform'})

dqm/dqm/home/templates/index.html
{% extends "layout.html" %}

{% block content %}
{% include "navigation.html" %}

<div class="container">
  <h1>{{ title }}
  </h1>
  <h2>{{ subtitle }}
  </h2>

  <h3> Instructions
  </h3>
  <div> Use Create display to create a display that will apear under the lists of
  Displays. When creating a display, users can select a template to use for the
  main display and then another template to use for each DQM app. </div>

  <div> In the list of displays, click the name of the display you want to see
  to access it and it will redirect you to a display with some general
  information like the run number, or what apps are currently sending. Each app
  can be clicked and we will be shown a display for that app only.</div>

</div>

{% endblock %}

dqm/dqm/home/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block pagestyles %}{% endblock %}
  {%load plotly_dash%}
  {% plotly_header %}

  {% load static%}
  {% block extra_header%}{% endblock%}

</head>

<body class="{{ template }}">
  {% block content %}{% endblock %}
</body>

 {% block post_body%}{% endblock%}
 {% plotly_footer %}

</html>

dqm/dqm/home/templates/navigation.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<style type="text/css" media="screen">
  .nav-link {
    padding: 0px 30px;
  }
  .nav-text {
    padding: 10px 20px;
  }
  .nav-text{
    color: white;
  }
  .nav-text:hover {
    background: #ffffff;
    border-radius: 32px;
    color: #070c49;
  }
  #result {
   position: fixed;
   top: 50px;
   max-width:870px;
   cursor: pointer;
   overflow-y: auto;
   max-height: 400px;
   box-sizing: border-box;
   z-index: 2001;
  }
</style>

<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous">
</script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js">
</script>

    <script>
    $(document).ready(function() {
        // $("select").select2({});
        $.ajaxSetup({ cache: false });

        var timer;
        $('#id_source').keyup(function() {
            clearTimeout(timer);
            $('#result').html('');
            $('#state').val('');

        var foodkind = $('#id_source').val();

        // Make Ajax Request and expect JSON-encoded data
        timer = setTimeout(function() {
        $.getJSON(
          '/aj/' + foodkind,
          function(data) {
          console.log(data)

            // Remove old options
            $('#id_choices').find('option').remove();
            $('#id_choices').find('.form-check').remove();

            // Add new items
            $.each(data, function(key, val) {
                // var option_item = ' <option value="' + val + '">' + val + ' </option>'
              var option_item = val.description
              // var option_item = ' <div class="form-check"> <input class="form-check-input" id="choices-0" name="choices" type="checkbox" value="' + val + '"> <label class="form-check-label" for="choices-0">' + val + ' </label> </div>'
              $('#result').append('<a href="' + val.url +'"><li class="list-group-item link-class">' + '<b>Display</b>: ' + val.name + ' ' + 'Description:' + val.description + '</li></a>');
            });
          }
        );

        }, 300);

        });

    $(document).on('click', function(event) {
    if (!$(event.target).closest('#result').length) {
      $('#result').html('');
    }
    });


    });

    $('#result').on('click', 'li', function() {
    var click_text = $(this).text().split('|');
    $('#id_source').val($.trim(click_text[0]));
    $("#result").html('');

 });

</script>

<nav class="navbar navbar-expand navbar-dark" style="background-color: #070c49;">
  <div class="container fluid">
    <a class="nav-link h5" href="{% url 'home' %}">
      <div class="nav-text">
        <b>Home
        </b>
      </div>
    </a>
    <a class="nav-link h5" href="{% url 'overview' %}">
      <div class="nav-text">
        <b>Displays
        </b>
      </div>
    </a>
    <a class="nav-link h5" href="{% url 'create display' %}">
      <div class="nav-text">
        <b>Create Display
        </b>
      </div>
    </a>
    <a class="nav-link h5" href="{% url 'templates' %}">
      <div class="nav-text">
        <b>Templates
        </b>
      </div>
    </a>
    <div class="d-flex flex-column mb-3">
      <ul class="list-group" id="result">
      </ul>
      <input type="text" name="search" id="id_source" placeholder="Search" class="form-control" />
    </div>
  </div>
</nav>

dqm/dqm/home/templates/test.html
<!DOCTYPE html>
<html>
 <head>
  <title>Webslesson Tutorial | Search HTML Table Data by using JQuery</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.js"></script>
  <style>
  #result {
   position: relative;
   width: 100%;
   max-width:870px;
   cursor: pointer;
   overflow-y: auto;
   max-height: 400px;
   box-sizing: border-box;
   z-index: 2001;
  }
  .link-class:hover{
   background-color:#f1f1f1;
  }
  </style>
 </head>
 <body>
  <br /><br />
  <div class="container" style="width:900px;">
   <h2 align="center">JSON Live Data Search using Ajax JQuery</h2>
   <h3 align="center">Employee Data</h3>   
   <br /><br />
   <div align="center">
    <input type="text" name="search" id="search" placeholder="Search Employee Details" class="form-control" />
   </div>
   <ul class="list-group" id="result"></ul>
   <br />
  </div>
 </body>
</html>

<script>
$(document).ready(function(){
 $.ajaxSetup({ cache: false });

 var timer;
 $('#search').keyup(function(){
     clearTimeout(timer);
     timer = setTimeout(function() {
         console.log('Stopped typing');
     }, 300);
  $('#result').html('');
  $('#state').val('');
  var searchField = $('#search').val();
  var expression = new RegExp(searchField, "i");
  $.getJSON('/get_json', function(data) {
   $.each(data, function(key, value){
    if (value.name.search(expression) != -1 || value.location.search(expression) != -1)
    {
     $('#result').append('<li class="list-group-item link-class"><img src="'+value.image+'" height="40" width="40" class="img-thumbnail" /> '+value.name+' | <span class="text-muted">'+value.location+'</span></li>');
    }
   });   
  });
 });
 
 $('#result').on('click', 'li', function() {
  var click_text = $(this).text().split('|');
  $('#search').val($.trim(click_text[0]));
  $("#result").html('');
 });

 $('#result').on('click', function() {
  $(this).html('');
 });

<!-- $('body').click(function(event) { -->
    
<!--     var log = $('#log'); -->
    
<!--     if($(event.target).is('#result')) { -->
<!--        log.html(event.target.id + ' was clicked.'); -->
<!--     } else { -->
<!--        $('#result').html('');     -->
<!--     } -->
<!-- }); -->

$(document).on('click', function(event) {
  if (!$(event.target).closest('#result').length) {
    // Hide the menus.
    $('#result').html('');

  }
});

});
</script>